# Generated by Django 3.2.25 on 2025-04-21 13:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('image', models.ImageField(default='../default_profile_ekxtnz', upload_to='images/')),
                ('about_me', models.TextField(blank=True, max_length=500)),
                ('city_of_origin', models.TextField(blank=True, max_length=255)),
                ('languages_spoken', models.TextField(blank=True, max_length=350)),
                ('story_title', models.TextField(blank=True, max_length=350)),
                ('proudest_moment', models.TextField(blank=True, max_length=350)),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
